apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: adrzio789/frontend:latest
        name: frontend
        ports:
        - containerPort: 5000
        env:
        - name: BACKEND_URL
          value: http://backend-service:5001
