apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: frontend
    repoURL: 'https://github.com/adrzio789/ArgoCD.git'
    targetRevision: main
  project: default
